name: Book Curation Service CD

on:
  push:
    branches:
      - main
      - oliveunji-patch-2

env:
  RESOURCE_GROUP: book-curation-rg
  CONTAINER_GROUP: book-curation-aci
  IMAGE_NAME: curation
  ACR_NAME: crcuration
  ACR_URL: 'crcuration.azurecr.io'
  TAG: latest
  
jobs:
  docker-image-build:
    name: Docker image build and push to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
      
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_URL }}
          username: ${{ env.ACR_NAME }}
          password: ${{ secrets.ACR_CREDENTIALS }}
      - run: |
          docker build . -t ${{ env.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          dns-name-label: ${{ env.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ env.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          registry-login-server: ${{ env.ACR_URL }}
          registry-username: ${{ env.ACR_NAME }}
          registry-password: ${{ secrets.ACR_CREDENTIALS }}
          name: ${{ env.CONTAINER_GROUP }}
          location: 'east us'
 
