name: Book Curation Service CD

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: book-curation-rg
  CONTAINER_GROUP: book-curation-aci
  IMAGE_NAME: curation
  ACR_NAME: crcuration
  ACR_URL: 'crcuration.azurecr.io'
  TAG: latest
  
jobs:
  docker-image-build:
    name: Docker image build and push to Azure Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Docker Image
        run: docker build . -t ${{ env.IMAGE_NAME }}

      - name: Tag Docker Image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ACR_URL }}
          username: ${{ env.ACR_NAME }}
          password: ${{ secrets.ACR_CREDENTIALS }}
          
      - name: Docker Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.ACR_URL }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az container restart --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CONTAINER_GROUP }}
