name: Book Curation Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test    
  
  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
    
  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Run Gitleaks
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          report_format: sarif

      - name: Upload SARIF report to Workflow Artifacts
        uses: actions/upload-artifact@v3
        if: always() && steps.gitleaks.outputs.exitcode != 0
        with:
          name: gitleaks
          path: |
            ${{ steps.gitleaks.outputs.report }}
      - name: Upload SARIF report to Code Scanning service
        if: always() && steps.gitleaks.outputs.exitcode != 0
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}
          category: gitleaks

